;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["components/basic-component/app-button/app-button"],{"04e2":function(t,n,e){"use strict";var r=function(){var t=this,n=t.$createElement;t._self._c},i=[];e.d(n,"a",function(){return r}),e.d(n,"b",function(){return i})},"3cd7":function(t,n,e){"use strict";var r=e("882f"),i=e.n(r);i.a},"3efb":function(t,n,e){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var r={props:{disabled:Boolean,type:String,round:Boolean,theme:String,height:String,fontSize:String,width:String,color:String,size:String,background:String,form:Boolean,arrangement:String,roundSize:String,padding:String,borderColor:String},data:function(){return{touch:!1}},methods:{handleClick:function(t){this.$emit("click",t)}},computed:{setHeight:function(){if(this.height)return this.height;switch(this.size){case"large":return 100;case"small":return 60;case"medium":return 80;default:return 80}}}};n.default=r},4751:function(t,n,e){"use strict";var r=e("f3b5"),i=e.n(r);i.a},"882f":function(t,n,e){},aec9:function(t,n,e){"use strict";e.r(n);var r=e("04e2"),i=e("c3a7");for(var u in i)"default"!==u&&function(t){e.d(n,t,function(){return i[t]})}(u);e("3cd7"),e("4751");var o=e("2877"),a=Object(o["a"])(i["default"],r["a"],r["b"],!1,null,"603e3f75",null);n["default"]=a.exports},c3a7:function(t,n,e){"use strict";e.r(n);var r=e("3efb"),i=e.n(r);for(var u in r)"default"!==u&&function(t){e.d(n,t,function(){return r[t]})}(u);n["default"]=i.a},f3b5:function(t,n,e){}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'components/basic-component/app-button/app-button-create-component',
    {
        'components/basic-component/app-button/app-button-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("aec9"))
        })
    },
    [['components/basic-component/app-button/app-button-create-component']]
]);                
