(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/app-shop/app-shop"],{"0f7e":function(t,n,e){},"400c":function(t,n,e){"use strict";e.r(n);var u=e("e4f4"),o=e("dad3");for(var a in o)"default"!==a&&function(t){e.d(n,t,function(){return o[t]})}(a);e("5a93");var r=e("2877"),i=Object(r["a"])(o["default"],u["a"],u["b"],!1,null,"528751f4",null);n["default"]=i.exports},"5a93":function(t,n,e){"use strict";var u=e("0f7e"),o=e.n(u);o.a},"9abd":function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var e={name:"app-shop",props:{list:{type:Array,default:function(){return[]}},navPicUrl:{type:String,default:function(){return""}},scorePicUrl:{type:String,default:function(){return""}},showName:{type:Boolean,default:function(){return!0}},showScore:{type:Boolean,default:function(){return!0}},showTel:{type:Boolean,default:function(){return!0}},scrollTop:{type:Number,default:function(){return 0}},value:{type:Boolean,default:function(){return!0}}},data:function(){return{height:0,request:!0}},created:function(){var n=this;t.getSystemInfo({success:function(t){n.height=t.windowHeight}})},methods:{autoEnd:function(){var t=this;this.$lazyLoadingData("app-shop").then(function(n){n[0].height+n[0].top<t.height&&(t.request=!1,t.$emit("input",t.request))})}},watch:{scrollTop:{handler:function(t,n){t>n&&this.request&&this.autoEnd()}}}};n.default=e}).call(this,e("f266")["default"])},dad3:function(t,n,e){"use strict";e.r(n);var u=e("9abd"),o=e.n(u);for(var a in u)"default"!==a&&function(t){e.d(n,t,function(){return u[t]})}(a);n["default"]=o.a},e4f4:function(t,n,e){"use strict";var u=function(){var t=this,n=t.$createElement;t._self._c},o=[];e.d(n,"a",function(){return u}),e.d(n,"b",function(){return o})}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/app-shop/app-shop-create-component',
    {
        'components/page-component/app-shop/app-shop-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('f266')['createComponent'](__webpack_require__("400c"))
        })
    },
    [['components/page-component/app-shop/app-shop-create-component']]
]);                
