;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["components/page-component/app-my-app/app-my-app"],{"36bc":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=n("2f62");function c(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(t);e&&(r=r.filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable})),n.push.apply(n,r)}return n}function o(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?c(n,!0).forEach(function(e){a(t,e,n[e])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):c(n).forEach(function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))})}return t}function a(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}var i={name:"app-my-app",data:function(){return{is_add_show:!1}},computed:o({},(0,r.mapState)("mallConfig",{setting:function(t){return t.mall.setting}})),methods:{close:function(){this.is_add_show=!1,this.$storage.setStorageSync("_IS_ADD_APP",!this.is_add_show)}},created:function(){this.is_add_show=!this.$storage.getStorageSync("_IS_ADD_APP")}};e.default=i},"46ac":function(t,e,n){"use strict";var r=function(){var t=this,e=t.$createElement;t._self._c},c=[];n.d(e,"a",function(){return r}),n.d(e,"b",function(){return c})},"6c6a":function(t,e,n){"use strict";var r=n("cc86"),c=n.n(r);c.a},cc86:function(t,e,n){},d7d6:function(t,e,n){"use strict";n.r(e);var r=n("46ac"),c=n("ff76");for(var o in c)"default"!==o&&function(t){n.d(e,t,function(){return c[t]})}(o);n("6c6a");var a=n("2877"),i=Object(a["a"])(c["default"],r["a"],r["b"],!1,null,"68b278f8",null);e["default"]=i.exports},ff76:function(t,e,n){"use strict";n.r(e);var r=n("36bc"),c=n.n(r);for(var o in r)"default"!==o&&function(t){n.d(e,t,function(){return r[t]})}(o);e["default"]=c.a}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'components/page-component/app-my-app/app-my-app-create-component',
    {
        'components/page-component/app-my-app/app-my-app-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("d7d6"))
        })
    },
    [['components/page-component/app-my-app/app-my-app-create-component']]
]);                
