<?php
/**
 * @copyright ©2021 南京千境网络科技有限公司
 * @link http://www.92mj.vip/
 * @author Qian
 */

namespace app\plugins\flash_sale\controllers\api;

use app\core\response\ApiCode;
use Yii;

class ApiController extends \app\controllers\api\ApiController
{
    public function beforeAction($action)
    {
        //权限判断
        $permission = Yii::$app->branch->childPermission(Yii::$app->mall->user->adminInfo);
        if (!in_array('flash_sale', $permission)) {
            Yii::$app->response->data = ['code' => ApiCode::CODE_ERROR, 'msg' => '无限时抢购权限'];
            return false;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
