<?php
/**
 * @author Qian
 * @copyright ©2021 南京千境网络科技有限公司
 * @link http://www.92mj.vip/
 */

namespace app\plugins\mch\controllers\api;


use app\controllers\api\filters\LoginFilter;
use app\plugins\mch\controllers\api\filter\MchLoginFilter;

class ApiController extends \app\controllers\api\ApiController
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'login' => [
                'class' => LoginFilter::class,
            ],
            'mchLogin' => [
                'class' => MchLoginFilter::class,
            ]
        ]);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
