<?php
/**
 * Created by qian_mall_app
 * @author Qian
 * Email: <qianjing.network@qq.com>
 */

namespace app\plugins\region\models;

class Order extends \app\models\Order
{
    public function getRegionOrder()
    {
        return $this->hasOne(RegionOrder::className(), ['order_id' => 'id']);
    }

    public function getOrderActionStatus($order)
    {
        $order = parent::getOrderActionStatus($order); // TODO: Change the autogenerated stub

        $order['is_print_send_template'] = 0;

        return $order;
    }
}