;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["components/page-component/goods/bd-xbc"],{"0c19":function(t,n,r){},"229b":function(t,n,r){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var a=function(){return r.e("components/basic-component/u-popup/u-popup").then(r.bind(null,"d55a"))},e={name:"bd-xbc",props:{attrGroups:Array,services:Array,attrList:Array,guaranteeTitle:String,guaranteePic:String,param_content:Array,param_name:String,type:String,goodsStock:Number,coAttr:{type:Number,default:1}},data:function(){return{attrStr:"请选择规格",serviceStr:"",paramStr:"",newAttrGroups:[],attrCount:[],attrName:"",pictureList:[],show:!1,isShow:""}},watch:{attrList:{deep:!0,immediate:!0,handler:function(t){var n="";this.$validation.isEmpty(t)?n="请选择规格":t.forEach(function(t){n+="".concat(t.attr_group_name,":").concat(t.attr_name," ")}),this.attrStr=n}},services:{immediate:!0,handler:function(){var t="";this.$validation.isEmpty(this.services)||this.services.forEach(function(n){t+="".concat(n.name," · ")}),t=t.substring(0,t.lastIndexOf(" · ")+1),this.serviceStr=t}},attrGroups:{immediate:!0,handler:function(t){var n=this;this.newAttrGroups=[],this.pictureList=[],this.attrCount=0,this.attrName="",t.forEach(function(t,r){n.attrName||(n.attrName=t.attr_group_name,t.attr_list.forEach(function(){n.attrCount+=1})),0===r&&t.attr_list.forEach(function(t){n.newAttrGroups.length<3&&n.newAttrGroups.push(t),t.pic_url&&n.pictureList.length<5&&n.pictureList.push(t.pic_url)})})}},param_content:{immediate:!0,handler:function(t){var n="";this.$validation.isEmpty(t)||t.forEach(function(t){n+="".concat(t.key," ")}),n=n.substring(0,n.lastIndexOf(" ")+1),this.paramStr=n}}},components:{uPopup:a},methods:{open:function(t){"attr"===t?this.$emit("openAttr"):(this.show=!0,this.isShow=t)}}};n.default=e},"417d2":function(t,n,r){"use strict";var a=r("0c19"),e=r.n(a);e.a},8639:function(t,n,r){"use strict";r.r(n);var a=r("df26"),e=r("f9ad");for(var i in e)"default"!==i&&function(t){r.d(n,t,function(){return e[t]})}(i);r("417d2");var o=r("2877"),u=Object(o["a"])(e["default"],a["a"],a["b"],!1,null,"a5cfaa88",null);n["default"]=u.exports},df26:function(t,n,r){"use strict";var a=function(){var t=this,n=t.$createElement;t._self._c;t._isMounted||(t.e0=function(n){t.show=!1},t.e1=function(n){t.show=!1})},e=[];r.d(n,"a",function(){return a}),r.d(n,"b",function(){return e})},f9ad:function(t,n,r){"use strict";r.r(n);var a=r("229b"),e=r.n(a);for(var i in a)"default"!==i&&function(t){r.d(n,t,function(){return a[t]})}(i);n["default"]=e.a}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'components/page-component/goods/bd-xbc-create-component',
    {
        'components/page-component/goods/bd-xbc-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("8639"))
        })
    },
    [['components/page-component/goods/bd-xbc-create-component']]
]);                
