(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/goods/bd-service"],{"1ee7":function(e,t,n){},"747e":function(e,t,n){"use strict";var r=function(){var e=this,t=e.$createElement,n=(e._self._c,encodeURIComponent(e.mall.setting.web_service_url));e.$mp.data=Object.assign({},{$root:{m0:n}})},o=[];n.d(t,"a",function(){return r}),n.d(t,"b",function(){return o})},"828d":function(e,t,n){"use strict";(function(e){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var r=n("2f62");function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter(function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable})),n.push.apply(n,r)}return n}function c(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(n,!0).forEach(function(t){u(e,t,n[t])}):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(n).forEach(function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))})}return e}function u(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}var a={name:"bd-service",computed:c({},(0,r.mapState)({mall:function(e){return e.mallConfig.mall}})),methods:{router:function(t){e.navigateTo({url:t})}}};t.default=a}).call(this,n("5486")["default"])},"85be":function(e,t,n){"use strict";var r=n("1ee7"),o=n.n(r);o.a},"861b":function(e,t,n){"use strict";n.r(t);var r=n("747e"),o=n("dac6");for(var c in o)"default"!==c&&function(e){n.d(t,e,function(){return o[e]})}(c);n("85be");var u=n("2877"),a=Object(u["a"])(o["default"],r["a"],r["b"],!1,null,"07728310",null);t["default"]=a.exports},dac6:function(e,t,n){"use strict";n.r(t);var r=n("828d"),o=n.n(r);for(var c in r)"default"!==c&&function(e){n.d(t,e,function(){return r[e]})}(c);t["default"]=o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/goods/bd-service-create-component',
    {
        'components/page-component/goods/bd-service-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('5486')['createComponent'](__webpack_require__("861b"))
        })
    },
    [['components/page-component/goods/bd-service-create-component']]
]);                
